### ISSUE TITLE
includeReducedFractions:false doesn't include both?

### ISSUE THREAD

**Issue by mhulse** [pure-css/grunt-pure-grids#8]
Hi,

Love Pure grids.

When I use the option:

``` js
includeReducedFractions : false
```

It doesn't appear that I get both regular and reduced fractional class names.
- Grunt: `0.4.5`
- Pure: `1.0.2`

My task:

``` js
/*----------------------------------( PURE )----------------------------------*/

/**
 * Generate custom grid units for Pure Grids.
 *
 * @see https://github.com/yahoo/grunt-pure-grids
 * @see http://purecss.io/grids/
 */

pure_grids: {

    responsive: {

        dest : './files/styles/partials/_grid-r.scss',

        options : {

            decimals : 14,                   // Grid unit width accuracy.
            includeOldIEWidths : false,      // Don't make grid units work properly in IE 6/7.
            includeReducedFractions : false, // Output class names in their regular and reduced fractional form.

            mediaQueries : {

                sm : 'all and (min-width: 640px)',
                md : 'all and (min-width: 960px)',
                lg : 'all and (min-width: 1280px)',
                xl : 'all and (min-width: 1600px)',

            },

        },

    },

},
```

Grid output (just part of it):

``` css
.pure-u-sm-1-5,
.pure-u-sm-2-5,
.pure-u-sm-3-5,
.pure-u-sm-4-5,
.pure-u-sm-5-5,
.pure-u-sm-1-24,
.pure-u-sm-2-24,
.pure-u-sm-3-24,
.pure-u-sm-4-24,
.pure-u-sm-5-24,
.pure-u-sm-6-24,
.pure-u-sm-7-24,
.pure-u-sm-8-24,
.pure-u-sm-9-24,
.pure-u-sm-10-24,
.pure-u-sm-11-24,
.pure-u-sm-12-24,
.pure-u-sm-13-24,
.pure-u-sm-14-24,
.pure-u-sm-15-24,
.pure-u-sm-16-24,
.pure-u-sm-17-24,
.pure-u-sm-18-24,
.pure-u-sm-19-24,
.pure-u-sm-20-24,
.pure-u-sm-21-24,
.pure-u-sm-22-24,
.pure-u-sm-23-24,
.pure-u-sm-24-24 {
    display: inline-block;
    *display: inline;
    zoom: 1;
    letter-spacing: normal;
    word-spacing: normal;
    vertical-align: top;
    text-rendering: auto;
}
```

Based on docs:

> Determines whether or not the output should only include the reduced fractions. Setting this to `true` means that all grid classnames would be provided in their reduced form (ex: `.pure-u-md-2-4` would be renamed to `.pure-u-md-1-2`). Setting this to `false` will output class names in their regular and reduced fractional form.

Shouldn't I see `1-12`?

Is it just me? Am I not understanding the documentation?

Thanks!
